### ISSUE TITLE
Code relative (rather than explicit) spacing

### ISSUE THREAD

**Issue by zacheadams** [zacheadams/unnecessary.fyi#5]
ex: instead of saying "this column needs to be 100 pts wide", it should be "this column needs to be 90% of the visible width", etc.

This will definitely be a major code overhaul, but we need it.  It might obviate the need to have a ["mobile site"](https://github.com/zacheadams/unnecessary.fyi/issues/3).

**Comment by helenkryan** [comment]
Changed to 

    <table>
  <tr>
    <th align="left" width="20%">score</th>
    <th align="left" width="45%">name</th>
    <th align="left" width="50%">type</th>
  </tr>  

from

  <table style="margin-left:25px">
 <col width="100">
 <col width="250">
 <col width="250">
  <tr>
    <th align="left">score</th>
    <th align="left">name</th>
    <th align="left">type</th>
  </tr>  

Also eliminated the left padding for the table
