### ISSUE TITLE
Get a favicon

### ISSUE THREAD

**Issue by zacheadams** [zacheadams/unnecessary.fyi#8]

**Comment by helenkryan** [comment]
Do you have any idea what you'd want this to be? You keep opening up tickets but I have no idea what you're thinking for any of them. 😆

**Comment by zacheadams** [comment]
I was just opening tickets so I'd have a to-do list of things, I didn't necessarily have any expected favicons, but https://favicon.io/ might be of use.  It seems we can use up to 192x192 PNG, but should probably have a lower resolution ICO file available?

IDK what I want it to be.  What do you think it should be?  We could use the [Unicode "Fork and Knife with Plate" emoji](https://emojipedia.org/fork-and-knife-with-plate/) in absence of an alternative.
